[Uxd 570] add bootcamp page
milvus-io/www.milvus.io pull request #390
Opened 2021-05-28 09:52 UTC by ThyeeZz

2021-05-28 10:32 UTC, nameczz commented on src/components/selector/v2/index.jsx
> +  console.log(label);
delete console

2021-05-28 10:32 UTC, nameczz commented on src/pages/bootcamp/index.module.less
> +        font-family: '思源黑体';
check font family

2021-05-28 10:57 UTC, shanghaikid requested changes

2021-05-28 10:57 UTC, shanghaikid commented on src/pages/bootcamp/index.jsx
> +          <p className={styles.title} lang={locale}>{benchmarkTitle}</p>
Title should be H1

2021-05-28 10:57 UTC, shanghaikid commented on src/pages/bootcamp/index.jsx
> +          <p className={styles.title} lang={locale} >{solutionTitle}</p>
solution should be list, please use ul,li

2021-05-28 13:18 UTC, Tumao727 commented on src/components/header/v2/secondHeader.jsx
> +              href = locale === 'en' ? href : `/cn${href}`;
don't directly change parameters,  use another variable or put the statement in <Link />

2021-05-29 02:15 UTC, shanghaikid requested changes

2021-05-29 02:15 UTC, shanghaikid commented on src/components/card/LinkCard/index.jsx
> +export default LinkCard;
no new line at the end of file

2021-05-29 02:15 UTC, shanghaikid commented on src/components/card/LinkCard/index.module.less
> +      font-family: '思源黑体';
same problem

2021-05-29 02:15 UTC, shanghaikid commented on src/components/card/bannerCard/index.jsx
> +export default BannerCard;
no new line at the end of file

2021-05-29 02:15 UTC, shanghaikid commented on src/components/card/bannerCard/index.jsx
> +          <div className={`${styles.mobileBannerCard} ${className}`}>
can we just use css to do this mobile styling? flex order?

2021-05-29 02:15 UTC, shanghaikid commented on src/components/card/bannerCard/index.module.less
> +        font-family: '思源黑体';
same font issue

2021-05-29 02:15 UTC, shanghaikid commented on src/components/card/bannerCard/index.module.less
> +      font-family: 'Inter';
what is the fallback of this font?

2021-05-29 02:15 UTC, shanghaikid commented on src/components/card/bannerCard/index.module.less
> +      font-family: 'Inter Bold';
fallback please

2021-05-29 02:15 UTC, shanghaikid commented on src/components/card/bannerCard/index.module.less
> +        font-family: '思源黑体';
same font

2021-05-29 02:15 UTC, shanghaikid commented on src/components/card/bannerCard/index.module.less
> +      font-family: '思源黑体';
why there are so many zh-cn font settings ? can we just use one ?

2021-05-29 02:15 UTC, shanghaikid commented on src/components/card/solutionCard/index.module.less
> +    -webkit-line-clamp: 2; //行数
remove chinese

2021-05-29 02:15 UTC, shanghaikid commented on src/pages/index.less
> +    max-width: 1400px;
why 1400, what is the value of @screen-lg-max

2021-06-01 02:41 UTC, merged